[build]
  publish = "public"
  functions = "functions"

[build.environment]
  HUGO_VERSION = "0.80.0"
  NODE_VERSION = "15.5.1"
  NPM_VERSION = "7.3.0"

[context.production]
  command = "hugo -b $URL --gc --minify && npm run build:functions"

[context.deploy-preview]
  command = "hugo -b $DEPLOY_PRIME_URL --gc --minify"

[context.branch-deploy]
  command = "hugo -b $DEPLOY_PRIME_URL --gc --minify"

  [[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "SAMEORIGIN"
    X-XSS-Protection = "0"
    X-Content-Type-Options = "nosniff"
    Content-Security-Policy = "default-src 'self'; style-src 'self' 'unsafe-inline' https://www.youtube.com  https://fonts.googleapis.com; form-action 'self'; script-src 'self'; connect-src 'self'; img-src 'self'; base-uri 'self'; frame-src 'self' https://www.youtube.com;"


[[redirects]]
  from = "/sharing"
  to = "https://meet.google.com/xmq-cshb-bik"
  status = 301
  force = false
 